"Segunda-feira": [
    { nome: "Desenvolvimento militar", series: "3x8-10", gif: "https://media.giphy.com/media/3o7qE1YN7aBOFPRw8E/giphy.gif" },
    { nome: "Elevação frontal", series: "3x10-12", gif: "https://media.giphy.com/media/xT9IgIc0lryrxvqVGM/giphy.gif" },
    { nome: "Elevação lateral", series: "3x10-12", gif: "https://media.giphy.com/media/l1J9EdzfOSgfyueLm/giphy.gif" },
    { nome: "Rosca direta", series: "3x10-12", gif: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif" },
    { nome: "Tríceps pulley", series: "3x10-12", gif: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif" },
    { nome: "Rosca martelo", series: "3x10-12", gif: "https://media.giphy.com/media/3o6Mbbs879ozZ9Yic0/giphy.gif" },
    { nome: "Tríceps testa", series: "3x10-12", gif: "https://media.giphy.com/media/26xBwdIuRJiAIqHwA/giphy.gif" },
  ],
  "Terça-feira": [
    { nome: "Supino reto", series: "3x8-10", gif: "https://media.giphy.com/media/3o6Mbbs879ozZ9Yic0/giphy.gif" },
    { nome: "Supino inclinado com halteres", series: "3x10-12", gif: "https://media.giphy.com/media/l4FGEq32lk6AZLYYI/giphy.gif" },
    { nome: "Crucifixo reto", series: "3x10-12", gif: "https://media.giphy.com/media/l0ExncehJzexFpRHq/giphy.gif" },
    { nome: "Remada na máquina", series: "3x10-12", gif: "https://media.giphy.com/media/l3vR85PnGsBwu1PFK/giphy.gif" },
    { nome: "Puxada na barra fixa", series: "3x8-10", gif: "https://media.giphy.com/media/3o6Zt6ML6BklcajjsA/giphy.gif" },
    { nome: "Pulldown", series: "3x10-12", gif: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif" },
  ],
  "Quarta-feira": [
    { nome: "Agachamento", series: "3x8-10", gif: "https://media.giphy.com/media/1zSZfrR1B0UbUZQa1u/giphy.gif" },
    { nome: "Leg press", series: "3x10-12", gif: "https://media.giphy.com/media/3o7qDZ26he1JqzNV4k/giphy.gif" },
    { nome: "Cadeira extensora", series: "3x12-15", gif: "https://media.giphy.com/media/l4FGv0w4HK9GJ6h0c/giphy.gif" },
    { nome: "Cadeira flexora", series: "3x12-15", gif: "https://media.giphy.com/media/l4FGF7MY7nF2H4Wog/giphy.gif" },
    { nome: "Panturrilha no leg press", series: "3x15-20", gif: "https://media.giphy.com/media/3o6ZtiT8OgEgyYhzKk/giphy.gif" },
    { nome: "Prancha abdominal", series: "3x30-60s", gif: "https://media.giphy.com/media/l1J3G5lf06vi58EIE/giphy.gif" },
    { nome: "Russian twist", series: "3x12-15", gif: "https://media.giphy.com/media/3ohs4A2fG42RqY09K8/giphy.gif" },
  ],
  "Quinta-feira": [
    { nome: "Desenvolvimento militar", series: "3x8-10", gif: "https://media.giphy.com/media/3o7qE1YN7aBOFPRw8E/giphy.gif" },
    { nome: "Elevação frontal", series: "3x10-12", gif: "https://media.giphy.com/media/xT9IgIc0lryrxvqVGM/giphy.gif" },
    { nome: "Elevação lateral", series: "3x10-12", gif: "https://media.giphy.com/media/l1J9EdzfOSgfyueLm/giphy.gif" },
    { nome: "Rosca direta", series: "3x10-12", gif: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif" },
    { nome: "Tríceps pulley", series: "3x10-12", gif: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif" },
    { nome: "Rosca martelo", series: "3x10-12", gif: "https://media.giphy.com/media/3o6Mbbs879ozZ9Yic0/giphy.gif" },
    { nome: "Tríceps testa", series: "3x10-12", gif: "https://media.giphy.com/media/26xBwdIuRJiAIqHwA/giphy.gif" },
  ],
  "Sexta-feira": [
    { nome: "Supino reto", series: "3x8-10", gif: "https://media.giphy.com/media/3o6Mbbs879ozZ9Yic0/giphy.gif" },
    { nome: "Supino inclinado com halteres", series: "3x10-12", gif: "https://media.giphy.com/media/l4FGEq32lk6AZLYYI/giphy.gif" },
    { nome: "Crucifixo reto", series: "3x10-12", gif: "https://media.giphy.com/media/l0ExncehJzexFpRHq/giphy.gif" },
    { nome: "Remada na máquina", series: "3x10-12", gif: "https://media.giphy.com/media/l3vR85PnGsBwu1PFK/giphy.gif" },
    { nome: "Puxada na barra fixa", series: "3x8-10", gif: "https://media.giphy.com/media/3o6Zt6ML6BklcajjsA/giphy.gif" },
    { nome: "Pulldown", series: "3x10-12", gif: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif" },
  ],
  "Sábado": [
    { nome: "Supino reto", series: "3x8-10", gif: "https://media.giphy.com/media/3o6Mbbs879ozZ9Yic0/giphy.gif" },
    { nome: "Agachamento", series: "3x8-10", gif: "https://media.giphy.com/media/1zSZfrR1B0UbUZQa1u/giphy.gif" },
    { nome: "Remada na máquina", series: "3x10-12", gif: "https://media.giphy.com/media/l3vR85PnGsBwu1PFK/giphy.gif" },
    { nome: "Desenvolvimento militar", series: "3x8-10", gif: "https://media.giphy.com/media/3o7qE1YN7aBOFPRw8E/giphy.gif" },
    { nome: "Puxada na barra fixa", series: "3x8-10", gif: "https://media.giphy.com/media/3o6Zt6ML6BklcajjsA/giphy.gif" },
    { nome: "Elevação lateral", series: "3x10-12", gif: "https://media.giphy.com/media/l1J9EdzfOSgfyueLm/giphy.gif" },
    { nome: "Burpees", series: "3x10", gif: "https://media.giphy.com/media/3o6ZtaO9BZHcOjmErm/giphy.gif" },
  ],
  "Domingo": [], // descanso